AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to deploy a Node.js Lambda function

Parameters:
  LambdaExecutionRoleArn:
    Description: "IAM Role ARN for Lambda execution with necessary permissions"
    Type: String
  LambdaRdsSecurityGroupId:
    Description: "Security Group ID for Lambda to access the RDS instance"
    Type: String

Resources:
  # Lambda Function
  MyLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: "TransactionLambdaFunction"
      Runtime: "nodejs22.x"
      Handler: "index.handler"
      Role: !Ref LambdaExecutionRoleArn
      Code:
        S3Bucket: "my-s3-lambda-code-bucket"
        S3Key: "lambda-app.zip"
      MemorySize: 128
      Timeout: 700
      VpcConfig:
        SubnetIds:
          - "subnet-042ad7bb9ea2d3926"
          - "subnet-0fe113b489031951d"
          - "subnet-0bba9d28301465792"
          - "subnet-029b09bb9e7288e18"
          - "subnet-0fbcfa84f1114589f"
          - "subnet-08cd8c9cd7cb873c4"
        SecurityGroupIds:
          - !Ref LambdaRdsSecurityGroupId
      Environment:
        Variables:
          NODE_ENV: "production"

Outputs:
  LambdaFunctionName:
    Description: "Name of the Lambda function"
    Value: !Ref MyLambdaFunction

  LambdaFunctionArn:
    Description: "ARN of the Lambda function"
    Value: !GetAtt MyLambdaFunction.Arn